name: SimpleParticles
main: particles.brainsynder.SimpleParticles
version: ${project.version}
depends: [SimpleAPI]
authors: [brainsynder, Thatsmusic99]
api-version: 1.13
commands:
  sp_test:
    description: TestCommand for SimpleParticles
  simpleparticles:
    description: Main command for SimpleParticles
    aliases: [sp,particles]